module.exports = {
  ROOM_ALREADY_EXIST: "Room already exists.",
  ROOM_CREATED: "Room Created successfully.",
  ROOM_NOT_EXIST: "This room is not exist.",
  ROOM_UPDATED: "Room updated successfully.",
  ROOM_DELETED: "Room deleted.",
  ROOMS_NOT_FOUND: "There are no rooms avalibale as per your search.",
  ROOM_FETCHED: "Rooms fetched successfully.",
  EMAIL_ALREADY_TAKEN: "Email is already taken",
  UNAUTHORIZED_USER: "Unauthorized - User not found",
  USER_REGISTERED: "User Registered Successfully",
  INCORRECT_PASSWORD: "Incorrect password",
  LOGIN_SUCCESSFUL: "LogIn Successfully",
  INCORRECT_MAIL: "Incorrect Email",
  RESET_LINK_SET_SUCCESSFULLY: "Reset link set successfully.",
  MAIL_NOT_REGISTERED: "Email is not registered with us",
  TOKEN_EXPIRED: "Your reset password token is expired, please try again",
  INCORRECT_TOKEN: "Incorrect Token",
  PASSWORD_UPDATED: "password update successfully",
};
